name: Update Profile Stars

on:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get total stars
        run: |
          TOTAL_STARS=$(curl -s "https://api.github.com/users/${{ github.repository_owner }}/repos?per_page=100" | jq '[.[].stargazers_count] | add')
          echo "Total stars: $TOTAL_STARS"
          sed -i "s|<!--TOTAL_STARS-->|⭐ $TOTAL_STARS stars|g" README.md

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Auto-update total stars"
          git push
